# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmaF4BPUoBp0DerW_eUxQtjsGzITQDym
"""

import argparse

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--mode",
        type=str,
        required=True,
        choices=["augment", "label"],
        help="Training mode"
    )
    args = ap.parse_args()

    if args.mode == "augment":
        from train_augment import main as train_main
    elif args.mode == "label":
        from train_label import main as train_main
    else:
        raise ValueError("Unknown training mode")

    train_main()

if __name__ == "__main__":
    main()