# -*- coding: utf-8 -*-
"""trainaftter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iaeEDv2SwOCD0fIWaCUqygQZRyAD1v3y
"""

import torch
import torch.nn as nn
import timm
from utils import get_dataloader, train_loop

def get_model(num_classes):
    model = timm.create_model(
        "vit_tiny_patch16_224",
        pretrained=True,
        num_classes=num_classes
    )
    return model

if __name__ == "__main__":
    train_loader, val_loader, num_classes = get_dataloader(augment=True)
    model = get_model(num_classes).cuda()

    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
    optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-4)

    train_loop(
        model,
        train_loader,
        val_loader,
        criterion,
        optimizer,
        save_path="models/vit_after.pt",
        log_dir="outputs/after"
    )