# -*- coding: utf-8 -*-
"""trainbefore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1S3LCTZ2AE8oTthE_uVbOQMlT4N0Vx_
"""

# train_before.py
import torch
import torch.nn as nn
import timm
from utils import get_dataloader, train_loop

def get_model(num_classes):
    model = timm.create_model(
        "vit_tiny_patch16_224",
        pretrained=True,
        num_classes=num_classes
    )
    return model

if __name__ == "__main__":
    train_loader, val_loader, num_classes = get_dataloader(augment=False)
    model = get_model(num_classes).cuda()

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=3e-4)

    train_loop(
        model,
        train_loader,
        val_loader,
        criterion,
        optimizer,
        save_path="models/vit_before.pt",
        log_dir="outputs/before"
    )